### ISSUE TITLE
musiclang_predict

### ISSUE THREAD

**Issue by GreatSarmad** [MusicLang/musiclang_predict#22]
When i am trying to add the musiclang_predict with pip it fails.

pip install musiclang_predict                   
Collecting musiclang_predict
  Using cached musiclang-predict-1.1.5.tar.gz (130 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        musiclang-predict_2505f9b1083a4343bd5f7c2de1fb024d\setup.py", line 68, in <module>
        long_description = (this_directory / "README.md").read_text()
        \anaconda3\envs\musiclang\lib\pathlib.py", line 1135, in read_text
          return f.read()
          anaconda3\envs\musiclang\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 342: character maps to <undefined>      
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by floriangardin** [comment]
Hello,
Seems there is a problem with the encoding of the readme in the repo on windows, I'll fix this in the next release.

If you want a quick workaround you can install it locally with pip and comment out the line that read the readme (by replacing it with empty text for example).
