### ISSUE TITLE
Audio Captioning

### ISSUE THREAD

**Issue by zfarrell13** [MusicLang/musiclang_predict#3]
this is an enhancement request rather than an issue, going to try to implement and work with this on my local machine today - but there is a tremendous use case for audio captioning.  Based on what i can see via skimming your code, it seems like you all have the resources and data to build a captioning algorithm.  would be really nice :)

**Comment by floriangardin** [comment]
Sounds very interesting. What's the specific use case you are thinking about, I don't fully get it ?
You'll probably want to PR from the [musiclang](https://github.com/MusicLang/musiclang) package directly as this one (musiclang_predict) is just the wrapper for prediction.

**Comment by zfarrell13** [comment]
will do.  use case is that for people building txt to audio, they will want to train their models on proprietary audio that hasnt been captioned yet and will need to apply captions before training.
